baseURL = "/"
languageCode = "en-us"
title = "Hugo Starter Site"
copyright = "Copyright: don't be a thief."

rssLimit = 20
staticDir = "static"
canonifyURLs = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[params]
  description = "A better starting point for building Hugo sites."

[markup.goldmark.renderer]
    unsafe = "true"
